### ISSUE TITLE
Problems with build

### ISSUE THREAD

**Issue by checksrc** [parkervcp/pterodactyl-panel-Dockerfile#3]
Hi @parkervcp ,
Using a compose.yml based on current version of your compose script - I'm trying to get Ptero going with the following; 

```
version: '2'
services:
  database:
    hostname: database
    image: mariadb:10.3
    expose:
      - "3306"
    ports:
      - "61782:3306"
    restart: always
    volumes:
      - "/srv/pterodactyl/database:/var/lib/mysql"
    environment:
      - "MYSQL_ROOT_PASSWORD=rootpass"
      - "MYSQL_DATABASE=pterodb"
      - "MYSQL_USER=ptero"
      - "MYSQL_PASSWORD=pteropass"
   network_mode: bridge
  
  Panel:
    hostname: Panel
    image: quay.io/parkervcp/pterodactyl-panel:latest
    ports:
      - "62328:80"
      - "64112:443"
    tty: true
    restart: always
    links:
      - database
    volumes:
      - "/srv/pterodactyl/var/:/var/www/html/var/"
      - "/srv/pterodactyl/certs/:/root/.caddy/"
    environment:
      - "db_host=a public ip"
      - "db_port=61782"
      - "db_name=pterodb"
      - "db_user=ptero"
      - "db_pass=pteropass"
      - "panel_url=a public ip"
      - "timezone=Europe/London"
      - "email_driver=mail"
      - "panel_email=admin@gmail.com"
      - "admin_email=email@gmail.com"
      - "admin_pass=password"
      - "admin_stat=1"
      - "ssl=false"
  network_mode: bridge
```

When it comes up I get the following logs for Ptero server;
```
2017-6-11 19:52:44 container initializing
2017-6-11 19:52:44 setting up ssl settings
2017-6-11 19:52:44 disabling ssl support
2017-6-11 19:52:44 continuing
2017-6-11 19:52:44      Found env file found. continuing start
2017-6-11 19:52:44 Activating privacy features... done.
2017-6-11 19:52:44 http://MY_PUBLIC_IP
```

The following logs for mariaDB;
```
2017-6-11 20:01:412017-06-11 19:01:41 140318089430912 [Note] options --log-slow-admin-statements, --log-queries-not-using-indexes and --log-slow-slave-statements have no effect if --log-slow-queries is not set
2017-6-11 20:01:412017-06-11 19:01:41 140318089430912 [Note] mysqld (mysqld 10.3.0-MariaDB-10.3.0+maria~jessie) starting as process 1 ...
2017-6-11 20:01:412017-06-11 19:01:41 140318089430912 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2017-6-11 20:01:412017-06-11 19:01:41 140318089430912 [Note] InnoDB: Uses event mutexes
2017-6-11 20:01:412017-06-11 19:01:41 140318089430912 [Note] InnoDB: Compressed tables use zlib 1.2.8
2017-6-11 20:01:412017-06-11 19:01:41 140318089430912 [Note] InnoDB: Using Linux native AIO
2017-6-11 20:01:412017-06-11 19:01:41 140318089430912 [Note] InnoDB: Number of pools: 1
2017-6-11 20:01:412017-06-11 19:01:41 140318089430912 [Note] InnoDB: Using SSE2 crc32 instructions
2017-6-11 20:01:412017-06-11 19:01:41 140318089430912 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
2017-6-11 20:01:412017-06-11 19:01:41 140318089430912 [Note] InnoDB: Completed initialization of buffer pool
2017-6-11 20:01:412017-06-11 19:01:41 140317145253632 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2017-6-11 20:01:412017-06-11 19:01:41 140318089430912 [Note] InnoDB: Highest supported file format is Barracuda.
2017-6-11 20:01:412017-06-11 19:01:41 140318089430912 [Note] InnoDB: Creating shared tablespace for temporary tables
2017-6-11 20:01:412017-06-11 19:01:41 140318089430912 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2017-6-11 20:01:412017-06-11 19:01:41 140318089430912 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2017-6-11 20:01:412017-06-11 19:01:41 140318089430912 [Note] InnoDB: 128 out of 128 rollback segments are active.
2017-6-11 20:01:412017-06-11 19:01:41 140318089430912 [Note] InnoDB: 5.7.14 started; log sequence number 1620154
2017-6-11 20:01:412017-06-11 19:01:41 140317000963840 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
2017-6-11 20:01:422017-06-11 19:01:42 140317000963840 [Note] InnoDB: Buffer pool(s) load completed at 170611 19:01:42
2017-6-11 20:01:422017-06-11 19:01:42 140318089430912 [Note] Plugin 'FEEDBACK' is disabled.
2017-6-11 20:01:422017-06-11 19:01:42 140318089430912 [Note] Server socket created on IP: '::'.
2017-6-11 20:01:422017-06-11 19:01:42 140318089430912 [Warning] 'proxies_priv' entry '@% root@database' ignored in --skip-name-resolve mode.
2017-6-11 20:01:422017-06-11 19:01:42 140318089430912 [Note] Reading of all Master_info entries succeded
2017-6-11 20:01:422017-06-11 19:01:42 140318089430912 [Note] Added new Master_info '' to hash table
2017-6-11 20:01:422017-06-11 19:01:42 140318089430912 [Note] mysqld: ready for connections.
2017-6-11 20:01:42Version: '10.3.0-MariaDB-10.3.0+maria~jessie'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
```

And the following error when I hit the IP:PORT of the Ptero Server. 
"Whoops, looks like something went wrong."

Any ideas? No errors reported by Ptero Server so seems a strange one.
